export interface PredefinedMeal {
  id: string;
  name: string;
  sinhalaName: string;
  category: string;
  calories: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  price: number;
}

export const PREDEFINED_MEALS: PredefinedMeal[] = [
  {
    "id": "m1",
    "name": "Vegetable Rice and Curry 🍛",
    "sinhalaName": "එළවළු බත් සහ කරි",
    "category": "Full Meals",
    "calories": 279,
    "protein": 30,
    "carbs": 16,
    "fat": 21,
    "price": 642
  },
  {
    "id": "m2",
    "name": "Vegetable Fried Rice 🍛",
    "sinhalaName": "එළවළු ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 619,
    "protein": 33,
    "carbs": 46,
    "fat": 17,
    "price": 565
  },
  {
    "id": "m3",
    "name": "Vegetable Kottu 🍛",
    "sinhalaName": "එළවළු කොත්තු",
    "category": "Full Meals",
    "calories": 336,
    "protein": 21,
    "carbs": 16,
    "fat": 9,
    "price": 224
  },
  {
    "id": "m4",
    "name": "Vegetable Noodles 🍛",
    "sinhalaName": "එළවළු නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 225,
    "protein": 19,
    "carbs": 57,
    "fat": 21,
    "price": 556
  },
  {
    "id": "m5",
    "name": "Vegetable Biryani 🍛",
    "sinhalaName": "එළවළු බිරියානි",
    "category": "Full Meals",
    "calories": 160,
    "protein": 27,
    "carbs": 11,
    "fat": 6,
    "price": 393
  },
  {
    "id": "m6",
    "name": "Chicken Rice and Curry 🍛",
    "sinhalaName": "කුකුල් මස් බත් සහ කරි",
    "category": "Full Meals",
    "calories": 429,
    "protein": 24,
    "carbs": 38,
    "fat": 16,
    "price": 403
  },
  {
    "id": "m7",
    "name": "Chicken Fried Rice 🍛",
    "sinhalaName": "කුකුල් මස් ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 373,
    "protein": 34,
    "carbs": 18,
    "fat": 10,
    "price": 203
  },
  {
    "id": "m8",
    "name": "Chicken Kottu 🍛",
    "sinhalaName": "කුකුල් මස් කොත්තු",
    "category": "Full Meals",
    "calories": 251,
    "protein": 23,
    "carbs": 23,
    "fat": 4,
    "price": 325
  },
  {
    "id": "m9",
    "name": "Chicken Noodles 🍛",
    "sinhalaName": "කුකුල් මස් නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 547,
    "protein": 34,
    "carbs": 48,
    "fat": 9,
    "price": 354
  },
  {
    "id": "m10",
    "name": "Chicken Biryani 🍛",
    "sinhalaName": "කුකුල් මස් බිරියානි",
    "category": "Full Meals",
    "calories": 361,
    "protein": 8,
    "carbs": 56,
    "fat": 6,
    "price": 543
  },
  {
    "id": "m11",
    "name": "Beef Rice and Curry 🍛",
    "sinhalaName": "හරක් මස් බත් සහ කරි",
    "category": "Full Meals",
    "calories": 545,
    "protein": 14,
    "carbs": 36,
    "fat": 20,
    "price": 325
  },
  {
    "id": "m12",
    "name": "Beef Fried Rice 🍛",
    "sinhalaName": "හරක් මස් ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 178,
    "protein": 9,
    "carbs": 49,
    "fat": 8,
    "price": 642
  },
  {
    "id": "m13",
    "name": "Beef Kottu 🍛",
    "sinhalaName": "හරක් මස් කොත්තු",
    "category": "Full Meals",
    "calories": 212,
    "protein": 21,
    "carbs": 49,
    "fat": 17,
    "price": 580
  },
  {
    "id": "m14",
    "name": "Beef Noodles 🍛",
    "sinhalaName": "හරක් මස් නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 631,
    "protein": 26,
    "carbs": 63,
    "fat": 18,
    "price": 602
  },
  {
    "id": "m15",
    "name": "Beef Biryani 🍛",
    "sinhalaName": "හරක් මස් බිරියානි",
    "category": "Full Meals",
    "calories": 403,
    "protein": 10,
    "carbs": 58,
    "fat": 4,
    "price": 500
  },
  {
    "id": "m16",
    "name": "Fish Rice and Curry 🍛",
    "sinhalaName": "මාළු බත් සහ කරි",
    "category": "Full Meals",
    "calories": 595,
    "protein": 25,
    "carbs": 47,
    "fat": 5,
    "price": 328
  },
  {
    "id": "m17",
    "name": "Fish Fried Rice 🍛",
    "sinhalaName": "මාළු ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 291,
    "protein": 24,
    "carbs": 55,
    "fat": 13,
    "price": 452
  },
  {
    "id": "m18",
    "name": "Fish Kottu 🍛",
    "sinhalaName": "මාළු කොත්තු",
    "category": "Full Meals",
    "calories": 520,
    "protein": 28,
    "carbs": 11,
    "fat": 16,
    "price": 331
  },
  {
    "id": "m19",
    "name": "Fish Noodles 🍛",
    "sinhalaName": "මාළු නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 378,
    "protein": 26,
    "carbs": 32,
    "fat": 18,
    "price": 402
  },
  {
    "id": "m20",
    "name": "Fish Biryani 🍛",
    "sinhalaName": "මාළු බිරියානි",
    "category": "Full Meals",
    "calories": 571,
    "protein": 26,
    "carbs": 15,
    "fat": 5,
    "price": 277
  },
  {
    "id": "m21",
    "name": "Egg Rice and Curry 🍛",
    "sinhalaName": "බිත්තර බත් සහ කරි",
    "category": "Full Meals",
    "calories": 327,
    "protein": 8,
    "carbs": 30,
    "fat": 16,
    "price": 150
  },
  {
    "id": "m22",
    "name": "Egg Fried Rice 🍛",
    "sinhalaName": "බිත්තර ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 209,
    "protein": 6,
    "carbs": 44,
    "fat": 9,
    "price": 349
  },
  {
    "id": "m23",
    "name": "Egg Kottu 🍛",
    "sinhalaName": "බිත්තර කොත්තු",
    "category": "Full Meals",
    "calories": 155,
    "protein": 17,
    "carbs": 52,
    "fat": 15,
    "price": 512
  },
  {
    "id": "m24",
    "name": "Egg Noodles 🍛",
    "sinhalaName": "බිත්තර නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 350,
    "protein": 33,
    "carbs": 31,
    "fat": 21,
    "price": 589
  },
  {
    "id": "m25",
    "name": "Egg Biryani 🍛",
    "sinhalaName": "බිත්තර බිරියානි",
    "category": "Full Meals",
    "calories": 606,
    "protein": 28,
    "carbs": 49,
    "fat": 11,
    "price": 167
  },
  {
    "id": "m26",
    "name": "Cheese Rice and Curry 🍛",
    "sinhalaName": "චීස් බත් සහ කරි",
    "category": "Full Meals",
    "calories": 525,
    "protein": 22,
    "carbs": 59,
    "fat": 12,
    "price": 367
  },
  {
    "id": "m27",
    "name": "Cheese Fried Rice 🍛",
    "sinhalaName": "චීස් ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 572,
    "protein": 24,
    "carbs": 57,
    "fat": 20,
    "price": 318
  },
  {
    "id": "m28",
    "name": "Cheese Kottu 🍛",
    "sinhalaName": "චීස් කොත්තු",
    "category": "Full Meals",
    "calories": 476,
    "protein": 32,
    "carbs": 23,
    "fat": 17,
    "price": 587
  },
  {
    "id": "m29",
    "name": "Cheese Noodles 🍛",
    "sinhalaName": "චීස් නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 348,
    "protein": 10,
    "carbs": 11,
    "fat": 10,
    "price": 567
  },
  {
    "id": "m30",
    "name": "Cheese Biryani 🍛",
    "sinhalaName": "චීස් බිරියානි",
    "category": "Full Meals",
    "calories": 620,
    "protein": 14,
    "carbs": 62,
    "fat": 8,
    "price": 477
  },
  {
    "id": "m31",
    "name": "Spicy Rice and Curry 🍛",
    "sinhalaName": "සැර බත් සහ කරි",
    "category": "Full Meals",
    "calories": 265,
    "protein": 18,
    "carbs": 63,
    "fat": 11,
    "price": 418
  },
  {
    "id": "m32",
    "name": "Spicy Fried Rice 🍛",
    "sinhalaName": "සැර ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 409,
    "protein": 6,
    "carbs": 44,
    "fat": 9,
    "price": 428
  },
  {
    "id": "m33",
    "name": "Spicy Kottu 🍛",
    "sinhalaName": "සැර කොත්තු",
    "category": "Full Meals",
    "calories": 294,
    "protein": 17,
    "carbs": 28,
    "fat": 7,
    "price": 225
  },
  {
    "id": "m34",
    "name": "Spicy Noodles 🍛",
    "sinhalaName": "සැර නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 595,
    "protein": 8,
    "carbs": 22,
    "fat": 7,
    "price": 426
  },
  {
    "id": "m35",
    "name": "Spicy Biryani 🍛",
    "sinhalaName": "සැර බිරියානි",
    "category": "Full Meals",
    "calories": 167,
    "protein": 18,
    "carbs": 38,
    "fat": 3,
    "price": 451
  },
  {
    "id": "m36",
    "name": "Special Rice and Curry 🍛",
    "sinhalaName": "විශේෂ බත් සහ කරි",
    "category": "Full Meals",
    "calories": 637,
    "protein": 8,
    "carbs": 55,
    "fat": 16,
    "price": 211
  },
  {
    "id": "m37",
    "name": "Special Fried Rice 🍛",
    "sinhalaName": "විශේෂ ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 562,
    "protein": 16,
    "carbs": 22,
    "fat": 2,
    "price": 224
  },
  {
    "id": "m38",
    "name": "Special Kottu 🍛",
    "sinhalaName": "විශේෂ කොත්තු",
    "category": "Full Meals",
    "calories": 433,
    "protein": 27,
    "carbs": 19,
    "fat": 14,
    "price": 383
  },
  {
    "id": "m39",
    "name": "Special Noodles 🍛",
    "sinhalaName": "විශේෂ නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 387,
    "protein": 27,
    "carbs": 33,
    "fat": 17,
    "price": 330
  },
  {
    "id": "m40",
    "name": "Special Biryani 🍛",
    "sinhalaName": "විශේෂ බිරියානි",
    "category": "Full Meals",
    "calories": 263,
    "protein": 13,
    "carbs": 32,
    "fat": 21,
    "price": 226
  },
  {
    "id": "m41",
    "name": "Mild Rice and Curry 🍛",
    "sinhalaName": "මෘදු බත් සහ කරි",
    "category": "Full Meals",
    "calories": 359,
    "protein": 19,
    "carbs": 62,
    "fat": 12,
    "price": 273
  },
  {
    "id": "m42",
    "name": "Mild Fried Rice 🍛",
    "sinhalaName": "මෘදු ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 590,
    "protein": 10,
    "carbs": 31,
    "fat": 11,
    "price": 483
  },
  {
    "id": "m43",
    "name": "Mild Kottu 🍛",
    "sinhalaName": "මෘදු කොත්තු",
    "category": "Full Meals",
    "calories": 177,
    "protein": 10,
    "carbs": 14,
    "fat": 6,
    "price": 630
  },
  {
    "id": "m44",
    "name": "Mild Noodles 🍛",
    "sinhalaName": "මෘදු නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 241,
    "protein": 14,
    "carbs": 25,
    "fat": 7,
    "price": 610
  },
  {
    "id": "m45",
    "name": "Mild Biryani 🍛",
    "sinhalaName": "මෘදු බිරියානි",
    "category": "Full Meals",
    "calories": 632,
    "protein": 19,
    "carbs": 32,
    "fat": 5,
    "price": 257
  },
  {
    "id": "m46",
    "name": "Mixed Rice and Curry 🍛",
    "sinhalaName": "මිශ්‍ර බත් සහ කරි",
    "category": "Full Meals",
    "calories": 367,
    "protein": 7,
    "carbs": 68,
    "fat": 12,
    "price": 174
  },
  {
    "id": "m47",
    "name": "Mixed Fried Rice 🍛",
    "sinhalaName": "මිශ්‍ර ෆ්‍රයිඩ් රයිස්",
    "category": "Full Meals",
    "calories": 424,
    "protein": 18,
    "carbs": 30,
    "fat": 8,
    "price": 338
  },
  {
    "id": "m48",
    "name": "Mixed Kottu 🍛",
    "sinhalaName": "මිශ්‍ර කොත්තු",
    "category": "Full Meals",
    "calories": 319,
    "protein": 32,
    "carbs": 66,
    "fat": 15,
    "price": 276
  },
  {
    "id": "m49",
    "name": "Mixed Noodles 🍛",
    "sinhalaName": "මිශ්‍ර නූඩ්ල්ස්",
    "category": "Full Meals",
    "calories": 530,
    "protein": 11,
    "carbs": 24,
    "fat": 19,
    "price": 218
  },
  {
    "id": "m50",
    "name": "Mixed Biryani 🍛",
    "sinhalaName": "මිශ්‍ර බිරියානි",
    "category": "Full Meals",
    "calories": 548,
    "protein": 25,
    "carbs": 47,
    "fat": 21,
    "price": 402
  },
  {
    "id": "m51",
    "name": "Vegetable Rolls 🍟",
    "sinhalaName": "එළවළු රෝල්ස්",
    "category": "Snacks",
    "calories": 180,
    "protein": 26,
    "carbs": 16,
    "fat": 4,
    "price": 179
  },
  {
    "id": "m52",
    "name": "Vegetable Patties 🍟",
    "sinhalaName": "එළවළු පැටිස්",
    "category": "Snacks",
    "calories": 250,
    "protein": 6,
    "carbs": 49,
    "fat": 3,
    "price": 292
  },
  {
    "id": "m53",
    "name": "Vegetable Cutlets 🍟",
    "sinhalaName": "එළවළු කටලට්",
    "category": "Snacks",
    "calories": 420,
    "protein": 13,
    "carbs": 54,
    "fat": 6,
    "price": 312
  },
  {
    "id": "m54",
    "name": "Vegetable Samosa 🍟",
    "sinhalaName": "එළවළු සමෝසා",
    "category": "Snacks",
    "calories": 327,
    "protein": 17,
    "carbs": 17,
    "fat": 13,
    "price": 567
  },
  {
    "id": "m55",
    "name": "Vegetable Vade 🍟",
    "sinhalaName": "එළවළු වඩේ",
    "category": "Snacks",
    "calories": 359,
    "protein": 9,
    "carbs": 45,
    "fat": 11,
    "price": 386
  },
  {
    "id": "m56",
    "name": "Chicken Rolls 🍟",
    "sinhalaName": "කුකුල් මස් රෝල්ස්",
    "category": "Snacks",
    "calories": 466,
    "protein": 19,
    "carbs": 36,
    "fat": 13,
    "price": 191
  },
  {
    "id": "m57",
    "name": "Chicken Patties 🍟",
    "sinhalaName": "කුකුල් මස් පැටිස්",
    "category": "Snacks",
    "calories": 565,
    "protein": 10,
    "carbs": 19,
    "fat": 12,
    "price": 201
  },
  {
    "id": "m58",
    "name": "Chicken Cutlets 🍟",
    "sinhalaName": "කුකුල් මස් කටලට්",
    "category": "Snacks",
    "calories": 182,
    "protein": 20,
    "carbs": 16,
    "fat": 11,
    "price": 444
  },
  {
    "id": "m59",
    "name": "Chicken Samosa 🍟",
    "sinhalaName": "කුකුල් මස් සමෝසා",
    "category": "Snacks",
    "calories": 499,
    "protein": 22,
    "carbs": 56,
    "fat": 17,
    "price": 210
  },
  {
    "id": "m60",
    "name": "Chicken Vade 🍟",
    "sinhalaName": "කුකුල් මස් වඩේ",
    "category": "Snacks",
    "calories": 616,
    "protein": 28,
    "carbs": 35,
    "fat": 9,
    "price": 182
  },
  {
    "id": "m61",
    "name": "Beef Rolls 🍟",
    "sinhalaName": "හරක් මස් රෝල්ස්",
    "category": "Snacks",
    "calories": 451,
    "protein": 8,
    "carbs": 38,
    "fat": 10,
    "price": 371
  },
  {
    "id": "m62",
    "name": "Beef Patties 🍟",
    "sinhalaName": "හරක් මස් පැටිස්",
    "category": "Snacks",
    "calories": 444,
    "protein": 16,
    "carbs": 26,
    "fat": 9,
    "price": 598
  },
  {
    "id": "m63",
    "name": "Beef Cutlets 🍟",
    "sinhalaName": "හරක් මස් කටලට්",
    "category": "Snacks",
    "calories": 487,
    "protein": 16,
    "carbs": 17,
    "fat": 17,
    "price": 174
  },
  {
    "id": "m64",
    "name": "Beef Samosa 🍟",
    "sinhalaName": "හරක් මස් සමෝසා",
    "category": "Snacks",
    "calories": 185,
    "protein": 15,
    "carbs": 65,
    "fat": 16,
    "price": 511
  },
  {
    "id": "m65",
    "name": "Beef Vade 🍟",
    "sinhalaName": "හරක් මස් වඩේ",
    "category": "Snacks",
    "calories": 477,
    "protein": 17,
    "carbs": 45,
    "fat": 20,
    "price": 251
  },
  {
    "id": "m66",
    "name": "Fish Rolls 🍟",
    "sinhalaName": "මාළු රෝල්ස්",
    "category": "Snacks",
    "calories": 154,
    "protein": 13,
    "carbs": 10,
    "fat": 12,
    "price": 243
  },
  {
    "id": "m67",
    "name": "Fish Patties 🍟",
    "sinhalaName": "මාළු පැටිස්",
    "category": "Snacks",
    "calories": 552,
    "protein": 26,
    "carbs": 61,
    "fat": 10,
    "price": 606
  },
  {
    "id": "m68",
    "name": "Fish Cutlets 🍟",
    "sinhalaName": "මාළු කටලට්",
    "category": "Snacks",
    "calories": 247,
    "protein": 22,
    "carbs": 19,
    "fat": 4,
    "price": 643
  },
  {
    "id": "m69",
    "name": "Fish Samosa 🍟",
    "sinhalaName": "මාළු සමෝසා",
    "category": "Snacks",
    "calories": 422,
    "protein": 23,
    "carbs": 32,
    "fat": 9,
    "price": 394
  },
  {
    "id": "m70",
    "name": "Fish Vade 🍟",
    "sinhalaName": "මාළු වඩේ",
    "category": "Snacks",
    "calories": 510,
    "protein": 18,
    "carbs": 67,
    "fat": 17,
    "price": 195
  },
  {
    "id": "m71",
    "name": "Egg Rolls 🍟",
    "sinhalaName": "බිත්තර රෝල්ස්",
    "category": "Snacks",
    "calories": 285,
    "protein": 30,
    "carbs": 37,
    "fat": 9,
    "price": 361
  },
  {
    "id": "m72",
    "name": "Egg Patties 🍟",
    "sinhalaName": "බිත්තර පැටිස්",
    "category": "Snacks",
    "calories": 445,
    "protein": 30,
    "carbs": 67,
    "fat": 3,
    "price": 639
  },
  {
    "id": "m73",
    "name": "Egg Cutlets 🍟",
    "sinhalaName": "බිත්තර කටලට්",
    "category": "Snacks",
    "calories": 565,
    "protein": 11,
    "carbs": 58,
    "fat": 17,
    "price": 370
  },
  {
    "id": "m74",
    "name": "Egg Samosa 🍟",
    "sinhalaName": "බිත්තර සමෝසා",
    "category": "Snacks",
    "calories": 514,
    "protein": 12,
    "carbs": 43,
    "fat": 8,
    "price": 413
  },
  {
    "id": "m75",
    "name": "Egg Vade 🍟",
    "sinhalaName": "බිත්තර වඩේ",
    "category": "Snacks",
    "calories": 353,
    "protein": 20,
    "carbs": 17,
    "fat": 14,
    "price": 214
  },
  {
    "id": "m76",
    "name": "Cheese Rolls 🍟",
    "sinhalaName": "චීස් රෝල්ස්",
    "category": "Snacks",
    "calories": 230,
    "protein": 30,
    "carbs": 55,
    "fat": 18,
    "price": 235
  },
  {
    "id": "m77",
    "name": "Cheese Patties 🍟",
    "sinhalaName": "චීස් පැටිස්",
    "category": "Snacks",
    "calories": 234,
    "protein": 15,
    "carbs": 34,
    "fat": 4,
    "price": 387
  },
  {
    "id": "m78",
    "name": "Cheese Cutlets 🍟",
    "sinhalaName": "චීස් කටලට්",
    "category": "Snacks",
    "calories": 163,
    "protein": 28,
    "carbs": 63,
    "fat": 21,
    "price": 508
  },
  {
    "id": "m79",
    "name": "Cheese Samosa 🍟",
    "sinhalaName": "චීස් සමෝසා",
    "category": "Snacks",
    "calories": 537,
    "protein": 32,
    "carbs": 31,
    "fat": 10,
    "price": 493
  },
  {
    "id": "m80",
    "name": "Cheese Vade 🍟",
    "sinhalaName": "චීස් වඩේ",
    "category": "Snacks",
    "calories": 445,
    "protein": 22,
    "carbs": 34,
    "fat": 14,
    "price": 309
  },
  {
    "id": "m81",
    "name": "Spicy Rolls 🍟",
    "sinhalaName": "සැර රෝල්ස්",
    "category": "Snacks",
    "calories": 638,
    "protein": 34,
    "carbs": 30,
    "fat": 11,
    "price": 390
  },
  {
    "id": "m82",
    "name": "Spicy Patties 🍟",
    "sinhalaName": "සැර පැටිස්",
    "category": "Snacks",
    "calories": 619,
    "protein": 25,
    "carbs": 36,
    "fat": 18,
    "price": 610
  },
  {
    "id": "m83",
    "name": "Spicy Cutlets 🍟",
    "sinhalaName": "සැර කටලට්",
    "category": "Snacks",
    "calories": 403,
    "protein": 31,
    "carbs": 61,
    "fat": 15,
    "price": 202
  },
  {
    "id": "m84",
    "name": "Spicy Samosa 🍟",
    "sinhalaName": "සැර සමෝසා",
    "category": "Snacks",
    "calories": 193,
    "protein": 33,
    "carbs": 12,
    "fat": 8,
    "price": 376
  },
  {
    "id": "m85",
    "name": "Spicy Vade 🍟",
    "sinhalaName": "සැර වඩේ",
    "category": "Snacks",
    "calories": 437,
    "protein": 10,
    "carbs": 67,
    "fat": 20,
    "price": 637
  },
  {
    "id": "m86",
    "name": "Special Rolls 🍟",
    "sinhalaName": "විශේෂ රෝල්ස්",
    "category": "Snacks",
    "calories": 493,
    "protein": 20,
    "carbs": 62,
    "fat": 16,
    "price": 196
  },
  {
    "id": "m87",
    "name": "Special Patties 🍟",
    "sinhalaName": "විශේෂ පැටිස්",
    "category": "Snacks",
    "calories": 643,
    "protein": 29,
    "carbs": 65,
    "fat": 19,
    "price": 270
  },
  {
    "id": "m88",
    "name": "Special Cutlets 🍟",
    "sinhalaName": "විශේෂ කටලට්",
    "category": "Snacks",
    "calories": 545,
    "protein": 10,
    "carbs": 29,
    "fat": 15,
    "price": 617
  },
  {
    "id": "m89",
    "name": "Special Samosa 🍟",
    "sinhalaName": "විශේෂ සමෝසා",
    "category": "Snacks",
    "calories": 648,
    "protein": 6,
    "carbs": 25,
    "fat": 13,
    "price": 550
  },
  {
    "id": "m90",
    "name": "Special Vade 🍟",
    "sinhalaName": "විශේෂ වඩේ",
    "category": "Snacks",
    "calories": 445,
    "protein": 26,
    "carbs": 52,
    "fat": 18,
    "price": 455
  },
  {
    "id": "m91",
    "name": "Mild Rolls 🍟",
    "sinhalaName": "මෘදු රෝල්ස්",
    "category": "Snacks",
    "calories": 458,
    "protein": 11,
    "carbs": 19,
    "fat": 6,
    "price": 394
  },
  {
    "id": "m92",
    "name": "Mild Patties 🍟",
    "sinhalaName": "මෘදු පැටිස්",
    "category": "Snacks",
    "calories": 477,
    "protein": 31,
    "carbs": 44,
    "fat": 5,
    "price": 535
  },
  {
    "id": "m93",
    "name": "Mild Cutlets 🍟",
    "sinhalaName": "මෘදු කටලට්",
    "category": "Snacks",
    "calories": 270,
    "protein": 14,
    "carbs": 60,
    "fat": 4,
    "price": 403
  },
  {
    "id": "m94",
    "name": "Mild Samosa 🍟",
    "sinhalaName": "මෘදු සමෝසා",
    "category": "Snacks",
    "calories": 164,
    "protein": 20,
    "carbs": 68,
    "fat": 2,
    "price": 247
  },
  {
    "id": "m95",
    "name": "Mild Vade 🍟",
    "sinhalaName": "මෘදු වඩේ",
    "category": "Snacks",
    "calories": 150,
    "protein": 28,
    "carbs": 53,
    "fat": 4,
    "price": 635
  },
  {
    "id": "m96",
    "name": "Mixed Rolls 🍟",
    "sinhalaName": "මිශ්‍ර රෝල්ස්",
    "category": "Snacks",
    "calories": 490,
    "protein": 5,
    "carbs": 23,
    "fat": 8,
    "price": 420
  },
  {
    "id": "m97",
    "name": "Mixed Patties 🍟",
    "sinhalaName": "මිශ්‍ර පැටිස්",
    "category": "Snacks",
    "calories": 449,
    "protein": 5,
    "carbs": 52,
    "fat": 9,
    "price": 170
  },
  {
    "id": "m98",
    "name": "Mixed Cutlets 🍟",
    "sinhalaName": "මිශ්‍ර කටලට්",
    "category": "Snacks",
    "calories": 454,
    "protein": 26,
    "carbs": 63,
    "fat": 10,
    "price": 497
  },
  {
    "id": "m99",
    "name": "Mixed Samosa 🍟",
    "sinhalaName": "මිශ්‍ර සමෝසා",
    "category": "Snacks",
    "calories": 575,
    "protein": 18,
    "carbs": 26,
    "fat": 11,
    "price": 379
  },
  {
    "id": "m100",
    "name": "Mixed Vade 🍟",
    "sinhalaName": "මිශ්‍ර වඩේ",
    "category": "Snacks",
    "calories": 197,
    "protein": 8,
    "carbs": 14,
    "fat": 4,
    "price": 634
  },
  {
    "id": "m101",
    "name": "Traditional Watalappan 🍰",
    "sinhalaName": "සාම්ප්‍රදායික වටලප්පන්",
    "category": "Desserts",
    "calories": 407,
    "protein": 33,
    "carbs": 25,
    "fat": 20,
    "price": 270
  },
  {
    "id": "m102",
    "name": "Vegetable Ice Cream 🍰",
    "sinhalaName": "එළවළු අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 169,
    "protein": 24,
    "carbs": 16,
    "fat": 10,
    "price": 596
  },
  {
    "id": "m103",
    "name": "Vegetable Pudding 🍰",
    "sinhalaName": "එළවළු පුඩිං",
    "category": "Desserts",
    "calories": 631,
    "protein": 18,
    "carbs": 12,
    "fat": 8,
    "price": 321
  },
  {
    "id": "m104",
    "name": "Vegetable Cake 🍰",
    "sinhalaName": "එළවළු කේක්",
    "category": "Desserts",
    "calories": 381,
    "protein": 32,
    "carbs": 13,
    "fat": 6,
    "price": 623
  },
  {
    "id": "m105",
    "name": "Vegetable Brownie 🍰",
    "sinhalaName": "එළවළු බ්‍රවුනී",
    "category": "Desserts",
    "calories": 428,
    "protein": 34,
    "carbs": 27,
    "fat": 16,
    "price": 436
  },
  {
    "id": "m106",
    "name": "Golden Watalappan 🍰",
    "sinhalaName": "රන් වටලප්පන්",
    "category": "Desserts",
    "calories": 536,
    "protein": 29,
    "carbs": 61,
    "fat": 7,
    "price": 578
  },
  {
    "id": "m107",
    "name": "Chicken Ice Cream 🍰",
    "sinhalaName": "කුකුල් මස් අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 217,
    "protein": 31,
    "carbs": 19,
    "fat": 11,
    "price": 167
  },
  {
    "id": "m108",
    "name": "Chicken Pudding 🍰",
    "sinhalaName": "කුකුල් මස් පුඩිං",
    "category": "Desserts",
    "calories": 166,
    "protein": 23,
    "carbs": 38,
    "fat": 18,
    "price": 580
  },
  {
    "id": "m109",
    "name": "Chicken Cake 🍰",
    "sinhalaName": "කුකුල් මස් කේක්",
    "category": "Desserts",
    "calories": 347,
    "protein": 11,
    "carbs": 28,
    "fat": 2,
    "price": 186
  },
  {
    "id": "m110",
    "name": "Chicken Brownie 🍰",
    "sinhalaName": "කුකුල් මස් බ්‍රවුනී",
    "category": "Desserts",
    "calories": 453,
    "protein": 30,
    "carbs": 50,
    "fat": 9,
    "price": 525
  },
  {
    "id": "m111",
    "name": "Cocoa Watalappan 🍰",
    "sinhalaName": "කොකෝ වටලප්පන්",
    "category": "Desserts",
    "calories": 588,
    "protein": 8,
    "carbs": 41,
    "fat": 13,
    "price": 151
  },
  {
    "id": "m112",
    "name": "Beef Ice Cream 🍰",
    "sinhalaName": "හරක් මස් අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 301,
    "protein": 30,
    "carbs": 35,
    "fat": 5,
    "price": 399
  },
  {
    "id": "m113",
    "name": "Beef Pudding 🍰",
    "sinhalaName": "හරක් මස් පුඩිං",
    "category": "Desserts",
    "calories": 405,
    "protein": 25,
    "carbs": 45,
    "fat": 13,
    "price": 274
  },
  {
    "id": "m114",
    "name": "Beef Cake 🍰",
    "sinhalaName": "හරක් මස් කේක්",
    "category": "Desserts",
    "calories": 547,
    "protein": 15,
    "carbs": 24,
    "fat": 16,
    "price": 647
  },
  {
    "id": "m115",
    "name": "Beef Brownie 🍰",
    "sinhalaName": "හරක් මස් බ්‍රවුනී",
    "category": "Desserts",
    "calories": 235,
    "protein": 22,
    "carbs": 13,
    "fat": 17,
    "price": 634
  },
  {
    "id": "m116",
    "name": "Coconut Watalappan 🍰",
    "sinhalaName": "පොල් වටලප්පන්",
    "category": "Desserts",
    "calories": 637,
    "protein": 25,
    "carbs": 36,
    "fat": 13,
    "price": 320
  },
  {
    "id": "m117",
    "name": "Fish Ice Cream 🍰",
    "sinhalaName": "මාළු අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 169,
    "protein": 25,
    "carbs": 49,
    "fat": 14,
    "price": 589
  },
  {
    "id": "m118",
    "name": "Fish Pudding 🍰",
    "sinhalaName": "මාළු පුඩිං",
    "category": "Desserts",
    "calories": 313,
    "protein": 22,
    "carbs": 60,
    "fat": 12,
    "price": 454
  },
  {
    "id": "m119",
    "name": "Fish Cake 🍰",
    "sinhalaName": "මාළු කේක්",
    "category": "Desserts",
    "calories": 520,
    "protein": 24,
    "carbs": 48,
    "fat": 10,
    "price": 589
  },
  {
    "id": "m120",
    "name": "Fish Brownie 🍰",
    "sinhalaName": "මාළු බ්‍රවුනී",
    "category": "Desserts",
    "calories": 386,
    "protein": 17,
    "carbs": 15,
    "fat": 17,
    "price": 321
  },
  {
    "id": "m121",
    "name": "Caramel Watalappan 🍰",
    "sinhalaName": "කැරමෙල් වටලප්පන්",
    "category": "Desserts",
    "calories": 178,
    "protein": 25,
    "carbs": 35,
    "fat": 17,
    "price": 253
  },
  {
    "id": "m122",
    "name": "Egg Ice Cream 🍰",
    "sinhalaName": "බිත්තර අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 583,
    "protein": 22,
    "carbs": 67,
    "fat": 13,
    "price": 537
  },
  {
    "id": "m123",
    "name": "Egg Pudding 🍰",
    "sinhalaName": "බිත්තර පුඩිං",
    "category": "Desserts",
    "calories": 201,
    "protein": 26,
    "carbs": 31,
    "fat": 13,
    "price": 399
  },
  {
    "id": "m124",
    "name": "Egg Cake 🍰",
    "sinhalaName": "බිත්තර කේක්",
    "category": "Desserts",
    "calories": 340,
    "protein": 9,
    "carbs": 19,
    "fat": 10,
    "price": 240
  },
  {
    "id": "m125",
    "name": "Egg Brownie 🍰",
    "sinhalaName": "බිත්තර බ්‍රවුනී",
    "category": "Desserts",
    "calories": 416,
    "protein": 11,
    "carbs": 36,
    "fat": 16,
    "price": 342
  },
  {
    "id": "m126",
    "name": "Signature Watalappan 🍰",
    "sinhalaName": "අත්සන් වටලප්පන්",
    "category": "Desserts",
    "calories": 285,
    "protein": 14,
    "carbs": 45,
    "fat": 7,
    "price": 515
  },
  {
    "id": "m127",
    "name": "Cheese Ice Cream 🍰",
    "sinhalaName": "චීස් අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 173,
    "protein": 30,
    "carbs": 30,
    "fat": 2,
    "price": 538
  },
  {
    "id": "m128",
    "name": "Cheese Pudding 🍰",
    "sinhalaName": "චීස් පුඩිං",
    "category": "Desserts",
    "calories": 576,
    "protein": 16,
    "carbs": 18,
    "fat": 15,
    "price": 551
  },
  {
    "id": "m129",
    "name": "Cheese Cake 🍰",
    "sinhalaName": "චීස් කේක්",
    "category": "Desserts",
    "calories": 617,
    "protein": 11,
    "carbs": 11,
    "fat": 13,
    "price": 336
  },
  {
    "id": "m130",
    "name": "Cheese Brownie 🍰",
    "sinhalaName": "චීස් බ්‍රවුනී",
    "category": "Desserts",
    "calories": 184,
    "protein": 14,
    "carbs": 50,
    "fat": 9,
    "price": 163
  },
  {
    "id": "m131",
    "name": "Spiced Watalappan 🍰",
    "sinhalaName": "කුළුබඩු වටලප්පන්",
    "category": "Desserts",
    "calories": 248,
    "protein": 28,
    "carbs": 45,
    "fat": 2,
    "price": 484
  },
  {
    "id": "m132",
    "name": "Spicy Ice Cream 🍰",
    "sinhalaName": "සැර අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 443,
    "protein": 8,
    "carbs": 37,
    "fat": 17,
    "price": 309
  },
  {
    "id": "m133",
    "name": "Spicy Pudding 🍰",
    "sinhalaName": "සැර පුඩිං",
    "category": "Desserts",
    "calories": 474,
    "protein": 11,
    "carbs": 15,
    "fat": 8,
    "price": 534
  },
  {
    "id": "m134",
    "name": "Spicy Cake 🍰",
    "sinhalaName": "සැර කේක්",
    "category": "Desserts",
    "calories": 315,
    "protein": 30,
    "carbs": 25,
    "fat": 15,
    "price": 257
  },
  {
    "id": "m135",
    "name": "Spicy Brownie 🍰",
    "sinhalaName": "සැර බ්‍රවුනී",
    "category": "Desserts",
    "calories": 425,
    "protein": 26,
    "carbs": 32,
    "fat": 9,
    "price": 264
  },
  {
    "id": "m136",
    "name": "Premium Watalappan 🍰",
    "sinhalaName": "ප්‍රීමියම් වටලප්පන්",
    "category": "Desserts",
    "calories": 412,
    "protein": 29,
    "carbs": 36,
    "fat": 21,
    "price": 289
  },
  {
    "id": "m137",
    "name": "Special Ice Cream 🍰",
    "sinhalaName": "විශේෂ අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 559,
    "protein": 30,
    "carbs": 67,
    "fat": 5,
    "price": 200
  },
  {
    "id": "m138",
    "name": "Special Pudding 🍰",
    "sinhalaName": "විශේෂ පුඩිං",
    "category": "Desserts",
    "calories": 306,
    "protein": 17,
    "carbs": 55,
    "fat": 7,
    "price": 236
  },
  {
    "id": "m139",
    "name": "Special Cake 🍰",
    "sinhalaName": "විශේෂ කේක්",
    "category": "Desserts",
    "calories": 577,
    "protein": 5,
    "carbs": 61,
    "fat": 4,
    "price": 290
  },
  {
    "id": "m140",
    "name": "Special Brownie 🍰",
    "sinhalaName": "විශේෂ බ්‍රවුනී",
    "category": "Desserts",
    "calories": 562,
    "protein": 5,
    "carbs": 43,
    "fat": 5,
    "price": 248
  },
  {
    "id": "m141",
    "name": "Classic Watalappan 🍰",
    "sinhalaName": "සාම්ප්‍රදායික වටලප්පන්",
    "category": "Desserts",
    "calories": 383,
    "protein": 11,
    "carbs": 12,
    "fat": 6,
    "price": 192
  },
  {
    "id": "m142",
    "name": "Mild Ice Cream 🍰",
    "sinhalaName": "මෘදු අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 232,
    "protein": 12,
    "carbs": 39,
    "fat": 11,
    "price": 268
  },
  {
    "id": "m143",
    "name": "Mild Pudding 🍰",
    "sinhalaName": "මෘදු පුඩිං",
    "category": "Desserts",
    "calories": 178,
    "protein": 17,
    "carbs": 15,
    "fat": 17,
    "price": 267
  },
  {
    "id": "m144",
    "name": "Mild Cake 🍰",
    "sinhalaName": "මෘදු කේක්",
    "category": "Desserts",
    "calories": 408,
    "protein": 10,
    "carbs": 61,
    "fat": 12,
    "price": 393
  },
  {
    "id": "m145",
    "name": "Mild Brownie 🍰",
    "sinhalaName": "මෘදු බ්‍රවුනී",
    "category": "Desserts",
    "calories": 409,
    "protein": 30,
    "carbs": 29,
    "fat": 5,
    "price": 358
  },
  {
    "id": "m146",
    "name": "Family Watalappan 🍰",
    "sinhalaName": "පවුල් වටලප්පන්",
    "category": "Desserts",
    "calories": 254,
    "protein": 31,
    "carbs": 59,
    "fat": 16,
    "price": 227
  },
  {
    "id": "m147",
    "name": "Mixed Ice Cream 🍰",
    "sinhalaName": "මිශ්‍ර අයිස්ක්‍රීම්",
    "category": "Desserts",
    "calories": 385,
    "protein": 33,
    "carbs": 24,
    "fat": 18,
    "price": 413
  },
  {
    "id": "m148",
    "name": "Mixed Pudding 🍰",
    "sinhalaName": "මිශ්‍ර පුඩිං",
    "category": "Desserts",
    "calories": 448,
    "protein": 9,
    "carbs": 60,
    "fat": 17,
    "price": 166
  },
  {
    "id": "m149",
    "name": "Mixed Cake 🍰",
    "sinhalaName": "මිශ්‍ර කේක්",
    "category": "Desserts",
    "calories": 172,
    "protein": 18,
    "carbs": 58,
    "fat": 18,
    "price": 194
  },
  {
    "id": "m150",
    "name": "Mixed Brownie 🍰",
    "sinhalaName": "මිශ්‍ර බ්‍රවුනී",
    "category": "Desserts",
    "calories": 338,
    "protein": 18,
    "carbs": 34,
    "fat": 15,
    "price": 430
  },
  {
    "id": "m151",
    "name": "Vegetable Green Salad 🥗",
    "sinhalaName": "එළවළු කොළ සලාද",
    "category": "Salads",
    "calories": 389,
    "protein": 33,
    "carbs": 43,
    "fat": 20,
    "price": 586
  },
  {
    "id": "m152",
    "name": "Vegetable Mixed Salad 🥗",
    "sinhalaName": "එළවළු මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 376,
    "protein": 14,
    "carbs": 69,
    "fat": 11,
    "price": 457
  },
  {
    "id": "m153",
    "name": "Garden Chicken Salad 🥗",
    "sinhalaName": "උද්‍යානයාත්මක කුකුල් මස් සලාද",
    "category": "Salads",
    "calories": 409,
    "protein": 30,
    "carbs": 20,
    "fat": 9,
    "price": 256
  },
  {
    "id": "m154",
    "name": "Vegetable Egg Salad 🥗",
    "sinhalaName": "එළවළු බිත්තර සලාද",
    "category": "Salads",
    "calories": 226,
    "protein": 13,
    "carbs": 47,
    "fat": 11,
    "price": 386
  },
  {
    "id": "m155",
    "name": "Vegetable Potato Salad 🥗",
    "sinhalaName": "එළවළු අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 175,
    "protein": 17,
    "carbs": 41,
    "fat": 14,
    "price": 279
  },
  {
    "id": "m156",
    "name": "Chicken Green Salad 🥗",
    "sinhalaName": "කුකුල් මස් කොළ සලාද",
    "category": "Salads",
    "calories": 286,
    "protein": 29,
    "carbs": 26,
    "fat": 5,
    "price": 417
  },
  {
    "id": "m157",
    "name": "Chicken Mixed Salad 🥗",
    "sinhalaName": "කුකුල් මස් මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 362,
    "protein": 33,
    "carbs": 36,
    "fat": 21,
    "price": 448
  },
  {
    "id": "m158",
    "name": "Double Chicken Salad 🥗",
    "sinhalaName": "ද්විත්ව කුකුල් මස් සලාද",
    "category": "Salads",
    "calories": 200,
    "protein": 20,
    "carbs": 25,
    "fat": 19,
    "price": 273
  },
  {
    "id": "m159",
    "name": "Chicken Egg Salad 🥗",
    "sinhalaName": "කුකුල් මස් බිත්තර සලාද",
    "category": "Salads",
    "calories": 541,
    "protein": 7,
    "carbs": 55,
    "fat": 4,
    "price": 396
  },
  {
    "id": "m160",
    "name": "Chicken Potato Salad 🥗",
    "sinhalaName": "කුකුල් මස් අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 275,
    "protein": 33,
    "carbs": 45,
    "fat": 3,
    "price": 232
  },
  {
    "id": "m161",
    "name": "Beef Green Salad 🥗",
    "sinhalaName": "හරක් මස් කොළ සලාද",
    "category": "Salads",
    "calories": 416,
    "protein": 11,
    "carbs": 48,
    "fat": 6,
    "price": 165
  },
  {
    "id": "m162",
    "name": "Beef Mixed Salad 🥗",
    "sinhalaName": "හරක් මස් මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 537,
    "protein": 28,
    "carbs": 27,
    "fat": 5,
    "price": 568
  },
  {
    "id": "m163",
    "name": "Mixed Protein Salad 🥗",
    "sinhalaName": "මිශ්‍ර ප්‍රෝටීන් සලාද",
    "category": "Salads",
    "calories": 373,
    "protein": 32,
    "carbs": 57,
    "fat": 11,
    "price": 196
  },
  {
    "id": "m164",
    "name": "Beef Egg Salad 🥗",
    "sinhalaName": "හරක් මස් බිත්තර සලාද",
    "category": "Salads",
    "calories": 283,
    "protein": 5,
    "carbs": 31,
    "fat": 5,
    "price": 352
  },
  {
    "id": "m165",
    "name": "Beef Potato Salad 🥗",
    "sinhalaName": "හරක් මස් අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 163,
    "protein": 8,
    "carbs": 49,
    "fat": 4,
    "price": 642
  },
  {
    "id": "m166",
    "name": "Fish Green Salad 🥗",
    "sinhalaName": "මාළු කොළ සලාද",
    "category": "Salads",
    "calories": 321,
    "protein": 13,
    "carbs": 49,
    "fat": 17,
    "price": 235
  },
  {
    "id": "m167",
    "name": "Fish Mixed Salad 🥗",
    "sinhalaName": "මාළු මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 290,
    "protein": 21,
    "carbs": 65,
    "fat": 11,
    "price": 344
  },
  {
    "id": "m168",
    "name": "Fish Chicken Salad 🥗",
    "sinhalaName": "මාළු කුකුල් මස් සලාද",
    "category": "Salads",
    "calories": 242,
    "protein": 22,
    "carbs": 45,
    "fat": 6,
    "price": 191
  },
  {
    "id": "m169",
    "name": "Fish Egg Salad 🥗",
    "sinhalaName": "මාළු බිත්තර සලාද",
    "category": "Salads",
    "calories": 512,
    "protein": 10,
    "carbs": 35,
    "fat": 12,
    "price": 515
  },
  {
    "id": "m170",
    "name": "Fish Potato Salad 🥗",
    "sinhalaName": "මාළු අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 297,
    "protein": 8,
    "carbs": 57,
    "fat": 14,
    "price": 641
  },
  {
    "id": "m171",
    "name": "Egg Green Salad 🥗",
    "sinhalaName": "බිත්තර කොළ සලාද",
    "category": "Salads",
    "calories": 338,
    "protein": 31,
    "carbs": 61,
    "fat": 16,
    "price": 507
  },
  {
    "id": "m172",
    "name": "Egg Mixed Salad 🥗",
    "sinhalaName": "බිත්තර මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 184,
    "protein": 22,
    "carbs": 43,
    "fat": 11,
    "price": 245
  },
  {
    "id": "m173",
    "name": "Egg Chicken Salad 🥗",
    "sinhalaName": "බිත්තර කුකුල් මස් සලාද",
    "category": "Salads",
    "calories": 299,
    "protein": 7,
    "carbs": 12,
    "fat": 17,
    "price": 645
  },
  {
    "id": "m174",
    "name": "Egg Egg Salad 🥗",
    "sinhalaName": "බිත්තර බිත්තර සලාද",
    "category": "Salads",
    "calories": 490,
    "protein": 6,
    "carbs": 11,
    "fat": 16,
    "price": 436
  },
  {
    "id": "m175",
    "name": "Egg Potato Salad 🥗",
    "sinhalaName": "බිත්තර අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 645,
    "protein": 20,
    "carbs": 23,
    "fat": 2,
    "price": 608
  },
  {
    "id": "m176",
    "name": "Cheese Green Salad 🥗",
    "sinhalaName": "චීස් කොළ සලාද",
    "category": "Salads",
    "calories": 522,
    "protein": 34,
    "carbs": 57,
    "fat": 21,
    "price": 377
  },
  {
    "id": "m177",
    "name": "Cheese Mixed Salad 🥗",
    "sinhalaName": "චීස් මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 582,
    "protein": 30,
    "carbs": 14,
    "fat": 3,
    "price": 593
  },
  {
    "id": "m178",
    "name": "Cheese Chicken Salad 🥗",
    "sinhalaName": "චීස් කුකුල් මස් සලාද",
    "category": "Salads",
    "calories": 483,
    "protein": 32,
    "carbs": 41,
    "fat": 20,
    "price": 446
  },
  {
    "id": "m179",
    "name": "Cheese Egg Salad 🥗",
    "sinhalaName": "චීස් බිත්තර සලාද",
    "category": "Salads",
    "calories": 371,
    "protein": 7,
    "carbs": 16,
    "fat": 18,
    "price": 412
  },
  {
    "id": "m180",
    "name": "Cheese Potato Salad 🥗",
    "sinhalaName": "චීස් අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 238,
    "protein": 16,
    "carbs": 14,
    "fat": 18,
    "price": 572
  },
  {
    "id": "m181",
    "name": "Spicy Green Salad 🥗",
    "sinhalaName": "සැර කොළ සලාද",
    "category": "Salads",
    "calories": 516,
    "protein": 7,
    "carbs": 30,
    "fat": 6,
    "price": 177
  },
  {
    "id": "m182",
    "name": "Spicy Mixed Salad 🥗",
    "sinhalaName": "සැර මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 173,
    "protein": 8,
    "carbs": 34,
    "fat": 17,
    "price": 245
  },
  {
    "id": "m183",
    "name": "Spicy Chicken Salad 🥗",
    "sinhalaName": "සැර කුකුල් මස් සලාද",
    "category": "Salads",
    "calories": 610,
    "protein": 23,
    "carbs": 40,
    "fat": 3,
    "price": 441
  },
  {
    "id": "m184",
    "name": "Spicy Egg Salad 🥗",
    "sinhalaName": "සැර බිත්තර සලාද",
    "category": "Salads",
    "calories": 531,
    "protein": 26,
    "carbs": 59,
    "fat": 8,
    "price": 620
  },
  {
    "id": "m185",
    "name": "Spicy Potato Salad 🥗",
    "sinhalaName": "සැර අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 315,
    "protein": 24,
    "carbs": 62,
    "fat": 16,
    "price": 405
  },
  {
    "id": "m186",
    "name": "Special Green Salad 🥗",
    "sinhalaName": "විශේෂ කොළ සලාද",
    "category": "Salads",
    "calories": 226,
    "protein": 34,
    "carbs": 50,
    "fat": 7,
    "price": 641
  },
  {
    "id": "m187",
    "name": "Special Mixed Salad 🥗",
    "sinhalaName": "විශේෂ මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 572,
    "protein": 11,
    "carbs": 68,
    "fat": 3,
    "price": 649
  },
  {
    "id": "m188",
    "name": "Special Chicken Salad 🥗",
    "sinhalaName": "විශේෂ කුකුල් මස් සලාද",
    "category": "Salads",
    "calories": 183,
    "protein": 13,
    "carbs": 61,
    "fat": 8,
    "price": 181
  },
  {
    "id": "m189",
    "name": "Special Egg Salad 🥗",
    "sinhalaName": "විශේෂ බිත්තර සලාද",
    "category": "Salads",
    "calories": 376,
    "protein": 33,
    "carbs": 56,
    "fat": 8,
    "price": 221
  },
  {
    "id": "m190",
    "name": "Special Potato Salad 🥗",
    "sinhalaName": "විශේෂ අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 150,
    "protein": 11,
    "carbs": 30,
    "fat": 19,
    "price": 334
  },
  {
    "id": "m191",
    "name": "Mild Green Salad 🥗",
    "sinhalaName": "මෘදු කොළ සලාද",
    "category": "Salads",
    "calories": 219,
    "protein": 26,
    "carbs": 54,
    "fat": 7,
    "price": 572
  },
  {
    "id": "m192",
    "name": "Mild Mixed Salad 🥗",
    "sinhalaName": "මෘදු මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 403,
    "protein": 29,
    "carbs": 47,
    "fat": 21,
    "price": 596
  },
  {
    "id": "m193",
    "name": "Mild Chicken Salad 🥗",
    "sinhalaName": "මෘදු කුකුල් මස් සලාද",
    "category": "Salads",
    "calories": 569,
    "protein": 21,
    "carbs": 53,
    "fat": 3,
    "price": 643
  },
  {
    "id": "m194",
    "name": "Mild Egg Salad 🥗",
    "sinhalaName": "මෘදු බිත්තර සලාද",
    "category": "Salads",
    "calories": 204,
    "protein": 31,
    "carbs": 47,
    "fat": 11,
    "price": 182
  },
  {
    "id": "m195",
    "name": "Mild Potato Salad 🥗",
    "sinhalaName": "මෘදු අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 381,
    "protein": 7,
    "carbs": 54,
    "fat": 8,
    "price": 335
  },
  {
    "id": "m196",
    "name": "Mixed Green Salad 🥗",
    "sinhalaName": "මිශ්‍ර කොළ සලාද",
    "category": "Salads",
    "calories": 597,
    "protein": 6,
    "carbs": 55,
    "fat": 21,
    "price": 515
  },
  {
    "id": "m197",
    "name": "Mixed Mixed Salad 🥗",
    "sinhalaName": "මිශ්‍ර මිශ්‍ර සලාද",
    "category": "Salads",
    "calories": 624,
    "protein": 32,
    "carbs": 32,
    "fat": 4,
    "price": 589
  },
  {
    "id": "m198",
    "name": "Mixed Chicken Salad 🥗",
    "sinhalaName": "මිශ්‍ර කුකුල් මස් සලාද",
    "category": "Salads",
    "calories": 241,
    "protein": 5,
    "carbs": 22,
    "fat": 11,
    "price": 390
  },
  {
    "id": "m199",
    "name": "Mixed Egg Salad 🥗",
    "sinhalaName": "මිශ්‍ර බිත්තර සලාද",
    "category": "Salads",
    "calories": 388,
    "protein": 28,
    "carbs": 44,
    "fat": 4,
    "price": 185
  },
  {
    "id": "m200",
    "name": "Mixed Potato Salad 🥗",
    "sinhalaName": "මිශ්‍ර අර්තාපල් සලාද",
    "category": "Salads",
    "calories": 252,
    "protein": 22,
    "carbs": 37,
    "fat": 13,
    "price": 340
  },
  {
    "id": "m201",
    "name": "Vegetable Milk Tea 🧃",
    "sinhalaName": "එළවළු කිරි තේ",
    "category": "Beverages",
    "calories": 599,
    "protein": 17,
    "carbs": 22,
    "fat": 16,
    "price": 421
  },
  {
    "id": "m202",
    "name": "Vegetable Plain Tea 🧃",
    "sinhalaName": "එළවළු ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 477,
    "protein": 10,
    "carbs": 66,
    "fat": 16,
    "price": 551
  },
  {
    "id": "m203",
    "name": "Vegetable Coffee 🧃",
    "sinhalaName": "එළවළු කෝපි",
    "category": "Beverages",
    "calories": 535,
    "protein": 14,
    "carbs": 24,
    "fat": 6,
    "price": 636
  },
  {
    "id": "m204",
    "name": "Vegetable Iced Coffee 🧃",
    "sinhalaName": "එළවළු අයිස් කෝපි",
    "category": "Beverages",
    "calories": 390,
    "protein": 33,
    "carbs": 50,
    "fat": 11,
    "price": 227
  },
  {
    "id": "m205",
    "name": "Vegetable Fruit Juice 🧃",
    "sinhalaName": "එළවළු පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 538,
    "protein": 28,
    "carbs": 34,
    "fat": 6,
    "price": 323
  },
  {
    "id": "m206",
    "name": "Chicken Milk Tea 🧃",
    "sinhalaName": "කුකුල් මස් කිරි තේ",
    "category": "Beverages",
    "calories": 421,
    "protein": 17,
    "carbs": 66,
    "fat": 5,
    "price": 318
  },
  {
    "id": "m207",
    "name": "Chicken Plain Tea 🧃",
    "sinhalaName": "කුකුල් මස් ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 343,
    "protein": 12,
    "carbs": 24,
    "fat": 12,
    "price": 317
  },
  {
    "id": "m208",
    "name": "Chicken Coffee 🧃",
    "sinhalaName": "කුකුල් මස් කෝපි",
    "category": "Beverages",
    "calories": 543,
    "protein": 25,
    "carbs": 38,
    "fat": 10,
    "price": 163
  },
  {
    "id": "m209",
    "name": "Chicken Iced Coffee 🧃",
    "sinhalaName": "කුකුල් මස් අයිස් කෝපි",
    "category": "Beverages",
    "calories": 359,
    "protein": 19,
    "carbs": 29,
    "fat": 4,
    "price": 423
  },
  {
    "id": "m210",
    "name": "Chicken Fruit Juice 🧃",
    "sinhalaName": "කුකුල් මස් පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 440,
    "protein": 14,
    "carbs": 36,
    "fat": 10,
    "price": 417
  },
  {
    "id": "m211",
    "name": "Beef Milk Tea 🧃",
    "sinhalaName": "හරක් මස් කිරි තේ",
    "category": "Beverages",
    "calories": 511,
    "protein": 8,
    "carbs": 18,
    "fat": 17,
    "price": 268
  },
  {
    "id": "m212",
    "name": "Beef Plain Tea 🧃",
    "sinhalaName": "හරක් මස් ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 208,
    "protein": 5,
    "carbs": 57,
    "fat": 14,
    "price": 393
  },
  {
    "id": "m213",
    "name": "Beef Coffee 🧃",
    "sinhalaName": "හරක් මස් කෝපි",
    "category": "Beverages",
    "calories": 428,
    "protein": 13,
    "carbs": 38,
    "fat": 19,
    "price": 497
  },
  {
    "id": "m214",
    "name": "Beef Iced Coffee 🧃",
    "sinhalaName": "හරක් මස් අයිස් කෝපි",
    "category": "Beverages",
    "calories": 222,
    "protein": 15,
    "carbs": 37,
    "fat": 3,
    "price": 215
  },
  {
    "id": "m215",
    "name": "Beef Fruit Juice 🧃",
    "sinhalaName": "හරක් මස් පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 595,
    "protein": 28,
    "carbs": 22,
    "fat": 2,
    "price": 307
  },
  {
    "id": "m216",
    "name": "Fish Milk Tea 🧃",
    "sinhalaName": "මාළු කිරි තේ",
    "category": "Beverages",
    "calories": 160,
    "protein": 5,
    "carbs": 15,
    "fat": 20,
    "price": 530
  },
  {
    "id": "m217",
    "name": "Fish Plain Tea 🧃",
    "sinhalaName": "මාළු ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 561,
    "protein": 18,
    "carbs": 67,
    "fat": 9,
    "price": 198
  },
  {
    "id": "m218",
    "name": "Fish Coffee 🧃",
    "sinhalaName": "මාළු කෝපි",
    "category": "Beverages",
    "calories": 330,
    "protein": 21,
    "carbs": 61,
    "fat": 9,
    "price": 386
  },
  {
    "id": "m219",
    "name": "Fish Iced Coffee 🧃",
    "sinhalaName": "මාළු අයිස් කෝපි",
    "category": "Beverages",
    "calories": 175,
    "protein": 32,
    "carbs": 64,
    "fat": 2,
    "price": 612
  },
  {
    "id": "m220",
    "name": "Fish Fruit Juice 🧃",
    "sinhalaName": "මාළු පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 354,
    "protein": 11,
    "carbs": 36,
    "fat": 7,
    "price": 644
  },
  {
    "id": "m221",
    "name": "Egg Milk Tea 🧃",
    "sinhalaName": "බිත්තර කිරි තේ",
    "category": "Beverages",
    "calories": 582,
    "protein": 19,
    "carbs": 64,
    "fat": 9,
    "price": 312
  },
  {
    "id": "m222",
    "name": "Egg Plain Tea 🧃",
    "sinhalaName": "බිත්තර ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 580,
    "protein": 14,
    "carbs": 45,
    "fat": 19,
    "price": 583
  },
  {
    "id": "m223",
    "name": "Egg Coffee 🧃",
    "sinhalaName": "බිත්තර කෝපි",
    "category": "Beverages",
    "calories": 395,
    "protein": 32,
    "carbs": 30,
    "fat": 9,
    "price": 195
  },
  {
    "id": "m224",
    "name": "Egg Iced Coffee 🧃",
    "sinhalaName": "බිත්තර අයිස් කෝපි",
    "category": "Beverages",
    "calories": 374,
    "protein": 33,
    "carbs": 24,
    "fat": 21,
    "price": 378
  },
  {
    "id": "m225",
    "name": "Egg Fruit Juice 🧃",
    "sinhalaName": "බිත්තර පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 226,
    "protein": 7,
    "carbs": 51,
    "fat": 9,
    "price": 278
  },
  {
    "id": "m226",
    "name": "Cheese Milk Tea 🧃",
    "sinhalaName": "චීස් කිරි තේ",
    "category": "Beverages",
    "calories": 205,
    "protein": 17,
    "carbs": 38,
    "fat": 21,
    "price": 247
  },
  {
    "id": "m227",
    "name": "Cheese Plain Tea 🧃",
    "sinhalaName": "චීස් ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 329,
    "protein": 32,
    "carbs": 62,
    "fat": 8,
    "price": 509
  },
  {
    "id": "m228",
    "name": "Cheese Coffee 🧃",
    "sinhalaName": "චීස් කෝපි",
    "category": "Beverages",
    "calories": 289,
    "protein": 32,
    "carbs": 55,
    "fat": 20,
    "price": 223
  },
  {
    "id": "m229",
    "name": "Cheese Iced Coffee 🧃",
    "sinhalaName": "චීස් අයිස් කෝපි",
    "category": "Beverages",
    "calories": 648,
    "protein": 6,
    "carbs": 65,
    "fat": 7,
    "price": 463
  },
  {
    "id": "m230",
    "name": "Cheese Fruit Juice 🧃",
    "sinhalaName": "චීස් පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 503,
    "protein": 27,
    "carbs": 52,
    "fat": 10,
    "price": 308
  },
  {
    "id": "m231",
    "name": "Spicy Milk Tea 🧃",
    "sinhalaName": "සැර කිරි තේ",
    "category": "Beverages",
    "calories": 200,
    "protein": 16,
    "carbs": 14,
    "fat": 12,
    "price": 506
  },
  {
    "id": "m232",
    "name": "Spicy Plain Tea 🧃",
    "sinhalaName": "සැර ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 340,
    "protein": 13,
    "carbs": 49,
    "fat": 4,
    "price": 591
  },
  {
    "id": "m233",
    "name": "Spicy Coffee 🧃",
    "sinhalaName": "සැර කෝපි",
    "category": "Beverages",
    "calories": 606,
    "protein": 27,
    "carbs": 39,
    "fat": 5,
    "price": 210
  },
  {
    "id": "m234",
    "name": "Spicy Iced Coffee 🧃",
    "sinhalaName": "සැර අයිස් කෝපි",
    "category": "Beverages",
    "calories": 224,
    "protein": 7,
    "carbs": 66,
    "fat": 9,
    "price": 164
  },
  {
    "id": "m235",
    "name": "Spicy Fruit Juice 🧃",
    "sinhalaName": "සැර පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 633,
    "protein": 12,
    "carbs": 15,
    "fat": 14,
    "price": 646
  },
  {
    "id": "m236",
    "name": "Special Milk Tea 🧃",
    "sinhalaName": "විශේෂ කිරි තේ",
    "category": "Beverages",
    "calories": 386,
    "protein": 34,
    "carbs": 23,
    "fat": 8,
    "price": 419
  },
  {
    "id": "m237",
    "name": "Special Plain Tea 🧃",
    "sinhalaName": "විශේෂ ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 209,
    "protein": 27,
    "carbs": 22,
    "fat": 21,
    "price": 155
  },
  {
    "id": "m238",
    "name": "Special Coffee 🧃",
    "sinhalaName": "විශේෂ කෝපි",
    "category": "Beverages",
    "calories": 513,
    "protein": 14,
    "carbs": 28,
    "fat": 19,
    "price": 581
  },
  {
    "id": "m239",
    "name": "Special Iced Coffee 🧃",
    "sinhalaName": "විශේෂ අයිස් කෝපි",
    "category": "Beverages",
    "calories": 374,
    "protein": 19,
    "carbs": 26,
    "fat": 4,
    "price": 594
  },
  {
    "id": "m240",
    "name": "Special Fruit Juice 🧃",
    "sinhalaName": "විශේෂ පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 270,
    "protein": 21,
    "carbs": 44,
    "fat": 20,
    "price": 349
  },
  {
    "id": "m241",
    "name": "Mild Milk Tea 🧃",
    "sinhalaName": "මෘදු කිරි තේ",
    "category": "Beverages",
    "calories": 567,
    "protein": 9,
    "carbs": 26,
    "fat": 15,
    "price": 164
  },
  {
    "id": "m242",
    "name": "Mild Plain Tea 🧃",
    "sinhalaName": "මෘදු ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 223,
    "protein": 15,
    "carbs": 52,
    "fat": 6,
    "price": 317
  },
  {
    "id": "m243",
    "name": "Mild Coffee 🧃",
    "sinhalaName": "මෘදු කෝපි",
    "category": "Beverages",
    "calories": 165,
    "protein": 12,
    "carbs": 57,
    "fat": 21,
    "price": 238
  },
  {
    "id": "m244",
    "name": "Mild Iced Coffee 🧃",
    "sinhalaName": "මෘදු අයිස් කෝපි",
    "category": "Beverages",
    "calories": 159,
    "protein": 13,
    "carbs": 25,
    "fat": 19,
    "price": 254
  },
  {
    "id": "m245",
    "name": "Mild Fruit Juice 🧃",
    "sinhalaName": "මෘදු පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 536,
    "protein": 30,
    "carbs": 22,
    "fat": 14,
    "price": 344
  },
  {
    "id": "m246",
    "name": "Mixed Milk Tea 🧃",
    "sinhalaName": "මිශ්‍ර කිරි තේ",
    "category": "Beverages",
    "calories": 352,
    "protein": 30,
    "carbs": 11,
    "fat": 3,
    "price": 586
  },
  {
    "id": "m247",
    "name": "Mixed Plain Tea 🧃",
    "sinhalaName": "මිශ්‍ර ප්ලේන් ටී",
    "category": "Beverages",
    "calories": 171,
    "protein": 11,
    "carbs": 14,
    "fat": 12,
    "price": 253
  },
  {
    "id": "m248",
    "name": "Mixed Coffee 🧃",
    "sinhalaName": "මිශ්‍ර කෝපි",
    "category": "Beverages",
    "calories": 203,
    "protein": 18,
    "carbs": 21,
    "fat": 20,
    "price": 331
  },
  {
    "id": "m249",
    "name": "Mixed Iced Coffee 🧃",
    "sinhalaName": "මිශ්‍ර අයිස් කෝපි",
    "category": "Beverages",
    "calories": 341,
    "protein": 31,
    "carbs": 24,
    "fat": 19,
    "price": 618
  },
  {
    "id": "m250",
    "name": "Mixed Fruit Juice 🧃",
    "sinhalaName": "මිශ්‍ර පළතුරු යුෂ",
    "category": "Beverages",
    "calories": 400,
    "protein": 33,
    "carbs": 38,
    "fat": 12,
    "price": 543
  },
  {
    "id": "m251",
    "name": "Vegetable Oats 🍲",
    "sinhalaName": "එළවළු ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 482,
    "protein": 23,
    "carbs": 49,
    "fat": 12,
    "price": 545
  },
  {
    "id": "m252",
    "name": "Vegetable Cornflakes 🍲",
    "sinhalaName": "එළවළු කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 539,
    "protein": 11,
    "carbs": 15,
    "fat": 16,
    "price": 326
  },
  {
    "id": "m253",
    "name": "Vegetable Fruit Bowl 🍲",
    "sinhalaName": "එළවළු පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 350,
    "protein": 14,
    "carbs": 63,
    "fat": 20,
    "price": 171
  },
  {
    "id": "m254",
    "name": "Vegetable Yogurt Bowl 🍲",
    "sinhalaName": "එළවළු යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 246,
    "protein": 33,
    "carbs": 15,
    "fat": 5,
    "price": 333
  },
  {
    "id": "m255",
    "name": "Vegetable Smoothie Bowl 🍲",
    "sinhalaName": "එළවළු ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 245,
    "protein": 14,
    "carbs": 63,
    "fat": 15,
    "price": 320
  },
  {
    "id": "m256",
    "name": "Chicken Oats 🍲",
    "sinhalaName": "කුකුල් මස් ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 448,
    "protein": 7,
    "carbs": 54,
    "fat": 21,
    "price": 216
  },
  {
    "id": "m257",
    "name": "Chicken Cornflakes 🍲",
    "sinhalaName": "කුකුල් මස් කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 271,
    "protein": 14,
    "carbs": 17,
    "fat": 6,
    "price": 429
  },
  {
    "id": "m258",
    "name": "Chicken Fruit Bowl 🍲",
    "sinhalaName": "කුකුල් මස් පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 613,
    "protein": 21,
    "carbs": 56,
    "fat": 17,
    "price": 288
  },
  {
    "id": "m259",
    "name": "Chicken Yogurt Bowl 🍲",
    "sinhalaName": "කුකුල් මස් යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 379,
    "protein": 29,
    "carbs": 22,
    "fat": 20,
    "price": 308
  },
  {
    "id": "m260",
    "name": "Chicken Smoothie Bowl 🍲",
    "sinhalaName": "කුකුල් මස් ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 492,
    "protein": 18,
    "carbs": 39,
    "fat": 12,
    "price": 374
  },
  {
    "id": "m261",
    "name": "Beef Oats 🍲",
    "sinhalaName": "හරක් මස් ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 635,
    "protein": 7,
    "carbs": 44,
    "fat": 21,
    "price": 625
  },
  {
    "id": "m262",
    "name": "Beef Cornflakes 🍲",
    "sinhalaName": "හරක් මස් කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 554,
    "protein": 8,
    "carbs": 34,
    "fat": 14,
    "price": 237
  },
  {
    "id": "m263",
    "name": "Beef Fruit Bowl 🍲",
    "sinhalaName": "හරක් මස් පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 172,
    "protein": 28,
    "carbs": 51,
    "fat": 15,
    "price": 342
  },
  {
    "id": "m264",
    "name": "Beef Yogurt Bowl 🍲",
    "sinhalaName": "හරක් මස් යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 226,
    "protein": 22,
    "carbs": 67,
    "fat": 21,
    "price": 613
  },
  {
    "id": "m265",
    "name": "Beef Smoothie Bowl 🍲",
    "sinhalaName": "හරක් මස් ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 492,
    "protein": 27,
    "carbs": 14,
    "fat": 10,
    "price": 294
  },
  {
    "id": "m266",
    "name": "Fish Oats 🍲",
    "sinhalaName": "මාළු ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 501,
    "protein": 11,
    "carbs": 29,
    "fat": 12,
    "price": 315
  },
  {
    "id": "m267",
    "name": "Fish Cornflakes 🍲",
    "sinhalaName": "මාළු කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 611,
    "protein": 8,
    "carbs": 18,
    "fat": 18,
    "price": 565
  },
  {
    "id": "m268",
    "name": "Fish Fruit Bowl 🍲",
    "sinhalaName": "මාළු පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 548,
    "protein": 22,
    "carbs": 20,
    "fat": 4,
    "price": 649
  },
  {
    "id": "m269",
    "name": "Fish Yogurt Bowl 🍲",
    "sinhalaName": "මාළු යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 592,
    "protein": 16,
    "carbs": 49,
    "fat": 5,
    "price": 417
  },
  {
    "id": "m270",
    "name": "Fish Smoothie Bowl 🍲",
    "sinhalaName": "මාළු ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 334,
    "protein": 21,
    "carbs": 49,
    "fat": 17,
    "price": 453
  },
  {
    "id": "m271",
    "name": "Egg Oats 🍲",
    "sinhalaName": "බිත්තර ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 317,
    "protein": 16,
    "carbs": 43,
    "fat": 13,
    "price": 169
  },
  {
    "id": "m272",
    "name": "Egg Cornflakes 🍲",
    "sinhalaName": "බිත්තර කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 226,
    "protein": 20,
    "carbs": 45,
    "fat": 16,
    "price": 576
  },
  {
    "id": "m273",
    "name": "Egg Fruit Bowl 🍲",
    "sinhalaName": "බිත්තර පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 606,
    "protein": 14,
    "carbs": 68,
    "fat": 18,
    "price": 354
  },
  {
    "id": "m274",
    "name": "Egg Yogurt Bowl 🍲",
    "sinhalaName": "බිත්තර යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 362,
    "protein": 7,
    "carbs": 30,
    "fat": 11,
    "price": 537
  },
  {
    "id": "m275",
    "name": "Egg Smoothie Bowl 🍲",
    "sinhalaName": "බිත්තර ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 285,
    "protein": 21,
    "carbs": 21,
    "fat": 3,
    "price": 505
  },
  {
    "id": "m276",
    "name": "Cheese Oats 🍲",
    "sinhalaName": "චීස් ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 311,
    "protein": 34,
    "carbs": 18,
    "fat": 3,
    "price": 389
  },
  {
    "id": "m277",
    "name": "Cheese Cornflakes 🍲",
    "sinhalaName": "චීස් කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 376,
    "protein": 32,
    "carbs": 42,
    "fat": 19,
    "price": 299
  },
  {
    "id": "m278",
    "name": "Cheese Fruit Bowl 🍲",
    "sinhalaName": "චීස් පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 296,
    "protein": 23,
    "carbs": 17,
    "fat": 16,
    "price": 261
  },
  {
    "id": "m279",
    "name": "Cheese Yogurt Bowl 🍲",
    "sinhalaName": "චීස් යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 330,
    "protein": 14,
    "carbs": 22,
    "fat": 7,
    "price": 580
  },
  {
    "id": "m280",
    "name": "Cheese Smoothie Bowl 🍲",
    "sinhalaName": "චීස් ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 235,
    "protein": 13,
    "carbs": 66,
    "fat": 17,
    "price": 298
  },
  {
    "id": "m281",
    "name": "Spicy Oats 🍲",
    "sinhalaName": "සැර ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 371,
    "protein": 20,
    "carbs": 68,
    "fat": 8,
    "price": 640
  },
  {
    "id": "m282",
    "name": "Spicy Cornflakes 🍲",
    "sinhalaName": "සැර කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 234,
    "protein": 32,
    "carbs": 37,
    "fat": 4,
    "price": 582
  },
  {
    "id": "m283",
    "name": "Spicy Fruit Bowl 🍲",
    "sinhalaName": "සැර පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 292,
    "protein": 26,
    "carbs": 43,
    "fat": 13,
    "price": 356
  },
  {
    "id": "m284",
    "name": "Spicy Yogurt Bowl 🍲",
    "sinhalaName": "සැර යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 584,
    "protein": 14,
    "carbs": 34,
    "fat": 4,
    "price": 444
  },
  {
    "id": "m285",
    "name": "Spicy Smoothie Bowl 🍲",
    "sinhalaName": "සැර ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 234,
    "protein": 15,
    "carbs": 35,
    "fat": 10,
    "price": 207
  },
  {
    "id": "m286",
    "name": "Special Oats 🍲",
    "sinhalaName": "විශේෂ ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 414,
    "protein": 28,
    "carbs": 51,
    "fat": 18,
    "price": 469
  },
  {
    "id": "m287",
    "name": "Special Cornflakes 🍲",
    "sinhalaName": "විශේෂ කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 373,
    "protein": 13,
    "carbs": 42,
    "fat": 17,
    "price": 492
  },
  {
    "id": "m288",
    "name": "Special Fruit Bowl 🍲",
    "sinhalaName": "විශේෂ පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 590,
    "protein": 13,
    "carbs": 51,
    "fat": 4,
    "price": 634
  },
  {
    "id": "m289",
    "name": "Special Yogurt Bowl 🍲",
    "sinhalaName": "විශේෂ යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 488,
    "protein": 30,
    "carbs": 28,
    "fat": 17,
    "price": 551
  },
  {
    "id": "m290",
    "name": "Special Smoothie Bowl 🍲",
    "sinhalaName": "විශේෂ ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 487,
    "protein": 7,
    "carbs": 15,
    "fat": 3,
    "price": 431
  },
  {
    "id": "m291",
    "name": "Mild Oats 🍲",
    "sinhalaName": "මෘදු ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 489,
    "protein": 25,
    "carbs": 61,
    "fat": 16,
    "price": 376
  },
  {
    "id": "m292",
    "name": "Mild Cornflakes 🍲",
    "sinhalaName": "මෘදු කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 545,
    "protein": 19,
    "carbs": 58,
    "fat": 5,
    "price": 529
  },
  {
    "id": "m293",
    "name": "Mild Fruit Bowl 🍲",
    "sinhalaName": "මෘදු පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 173,
    "protein": 27,
    "carbs": 54,
    "fat": 2,
    "price": 308
  },
  {
    "id": "m294",
    "name": "Mild Yogurt Bowl 🍲",
    "sinhalaName": "මෘදු යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 593,
    "protein": 5,
    "carbs": 44,
    "fat": 6,
    "price": 383
  },
  {
    "id": "m295",
    "name": "Mild Smoothie Bowl 🍲",
    "sinhalaName": "මෘදු ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 298,
    "protein": 13,
    "carbs": 42,
    "fat": 8,
    "price": 468
  },
  {
    "id": "m296",
    "name": "Mixed Oats 🍲",
    "sinhalaName": "මිශ්‍ර ඕට්ස්",
    "category": "Breakfast Bowls",
    "calories": 629,
    "protein": 10,
    "carbs": 62,
    "fat": 7,
    "price": 374
  },
  {
    "id": "m297",
    "name": "Mixed Cornflakes 🍲",
    "sinhalaName": "මිශ්‍ර කෝන්ෆ්ලේක්ස්",
    "category": "Breakfast Bowls",
    "calories": 451,
    "protein": 29,
    "carbs": 48,
    "fat": 6,
    "price": 599
  },
  {
    "id": "m298",
    "name": "Mixed Fruit Bowl 🍲",
    "sinhalaName": "මිශ්‍ර පළතුරු බෝල්",
    "category": "Breakfast Bowls",
    "calories": 620,
    "protein": 10,
    "carbs": 61,
    "fat": 5,
    "price": 294
  },
  {
    "id": "m299",
    "name": "Mixed Yogurt Bowl 🍲",
    "sinhalaName": "මිශ්‍ර යෝගට් බෝල්",
    "category": "Breakfast Bowls",
    "calories": 246,
    "protein": 16,
    "carbs": 18,
    "fat": 19,
    "price": 302
  },
  {
    "id": "m300",
    "name": "Mixed Smoothie Bowl 🍲",
    "sinhalaName": "මිශ්‍ර ස්මූති බෝල්",
    "category": "Breakfast Bowls",
    "calories": 351,
    "protein": 21,
    "carbs": 11,
    "fat": 2,
    "price": 428
  }
];